
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UploadExcelToSQLServer
{

using System;
    using System.Collections.Generic;
    
public partial class Lowes_Daily_List
{

    public string skunum { get; set; }

    public int salesUnit { get; set; }

    public string PartNum { get; set; }

    public string Description { get; set; }

    public int Qty { get; set; }

    public string datebackinstock { get; set; }

    public string availableqty { get; set; }

    public string status { get; set; }

    public Nullable<System.DateTime> discont_date { get; set; }

    public string Company { get; set; }

    public int ID { get; set; }

}

}
